
[workspace]
members = [
    "audio-engine-common",
    "audio-engine-notes",

    "audio-engine-fm",
    "audio-engine-sample",
    "audio-engine-instruments",

    "audio-engine-sequencer",
    "audio-engine-tracker",
    "audio-engine-player",
]

resolver = "2"

[profile.dev]
lto = false

[profile.release]
lto = true
