[package]
name = "audio-engine-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="audio_engine_common"
path="src/lib.rs"

[dependencies]
png = "0.17.10"
