[package]
name = "audio-engine-fm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="audio_engine_fm"
path="src/lib.rs"

[dependencies]
cpal = "*"

[[examples]]
name="experiment"
